import { ElementRef, AfterViewChecked, EventEmitter } from '@angular/core';
import { ResizableEvent } from '../resizable/types';
import * as i0 from "@angular/core";
export declare class ModalComponent implements AfterViewChecked {
    private element;
    scrollTopEnable: boolean;
    maximizable: boolean;
    backdrop: boolean;
    inViewport: boolean;
    isResizable: boolean;
    closeModal: EventEmitter<boolean>;
    modalRoot: ElementRef;
    modalBody: ElementRef;
    modalHeader: ElementRef;
    modalFooter: ElementRef;
    closeIcon: ElementRef;
    visible: boolean;
    executePostDisplayActions: boolean;
    maximized: boolean;
    preMaximizeRootWidth: number;
    preMaximizeRootHeight: number;
    preMaximizeBodyHeight: number;
    preMaximizePageX: number;
    preMaximizePageY: number;
    dragEventTarget: MouseEvent | TouchEvent;
    constructor(element: ElementRef);
    ngAfterViewChecked(): void;
    onKeyDown(event: any): void;
    onWindowResize(): void;
    show(): void;
    hide(): void;
    center(): void;
    initDrag(event: MouseEvent | TouchEvent): void;
    onResize(event: ResizableEvent): void;
    calcBodyHeight(): void;
    getMaxModalIndex(): number;
    focusLastModal(): void;
    toggleMaximize(event: any): void;
    maximize(): void;
    revertMaximize(): void;
    moveOnTop(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ModalComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ModalComponent, "app-modal", never, { "scrollTopEnable": "scrollTopEnable"; "maximizable": "maximizable"; "backdrop": "backdrop"; "inViewport": "inViewport"; "isResizable": "isResizable"; }, { "closeModal": "closeModal"; }, never, [".app-modal-header", ".app-modal-body", ".app-modal-footer"]>;
}
